version: '3.8'
services:
  sample:
    container_name: product_list
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/product_list'
      - '/product_list/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true