export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_CLEAR_ALL = 'FILTER_CLEAR_ALL';
